sudo: false
language: rust

env:
  - FLAGS=
  - FLAGS="--features glium-support"
script:
  - cargo build --verbose $(echo $FLAGS)
  - cargo test  --verbose $(echo $FLAGS)

cache:
  directories:
    - ~/.cargo
    - target

notifications:
  irc:
    nick: obj-rs
    channels: 'ircs://irc.uriirc.org:16664#hyeon'
    template: '#%{build_number} %{result}, %{build_url}'
    skip_join: true
