# Copyright 2014-2017 Hyeon Kim
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

[package]
name = "obj-rs"
version = "0.4.20"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
homepage = "https://github.com/simnalamburt/obj-rs"
repository = "https://github.com/simnalamburt/obj-rs"
documentation = "https://simnalamburt.github.io/obj-rs/"
license = "Apache-2.0/MIT"
keywords = ["graphics", "obj", "WaveFront", "3D", "parser"]
readme = "README.md"

description = """
Wavefront obj parser for Rust. It handles both 'obj' and 'mtl' formats.
"""

[lib]
name = "obj"

[features]
glium-support = ["glium"]

[dependencies]
glium = { version = "0.14.0", default-features = false, optional = true }
vec_map = "0.6.0"
serde = "1.0"
serde_derive = "1.0"


[[example]]
name = "glium"

[dev_dependencies]
glium = "0.14.0"
