[package]
name = "obj-rs"
version = "0.4.10"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
homepage = "https://github.com/simnalamburt/obj-rs"
repository = "https://github.com/simnalamburt/obj-rs"
documentation = "https://simnalamburt.github.io/obj-rs/"
license = "BSD-2-Clause"
keywords = ["graphics", "obj", "WaveFront", "3D", "parser"]
readme = "README.md"

description = """
Wavefront obj parser for Rust. It handles both 'obj' and 'mtl' formats.
"""

[lib]
name = "obj"

[features]
glium-support = ["glium"]

[dependencies]
glium = { version = "0.8.2", default-features = false, optional = true }
vec_map = "0.3.0"
