[package]
name = "sampleapp-vulkano"
version = "0.1.0"
authors = ["Govind Venkatesh <venakteshgovind1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.19.0"
vulkano-win = "0.19"
vulkano-shaders = "0.19.0"
winit = "0.22.2"
nalgebra = "0.18"
obj-rs = { path = "../obj-rs", default-features = false, features = ["vulkano"] }
